blank_issues_enabled: true

contact_links:
    - name: ğŸ‘· Soporte
      url: https://caefisica.com/contacto/
      about: Si lo consideras apropiado, puede dirigir sus consultas y dudas aquÃ­

    - name: â“ Preguntas y Discusiones
      url: https://github.com/caefisica/web/discussions
      about: Utiliza las discusiones de GitHub para las preguntas y discusiones de tipo tablÃ³n de anuncios
