backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
show_preview_links: true
locale: 'es'
logo_url: /images/logo.svg
slug:
  clean_accents: true
collections:
  - name: blog
    label: Blogs
    folder: content/blog/
    create: true
    slug: "{{slug}}"
    nested:
      depth: 1000
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    editor:
      preview: true
    fields:
      - { label: 'T√≠tulo', name: 'title', widget: 'string' }
      - { label: 'Autor (ej. List [ "tunombre" ])', name: 'contributors', widget: 'string' }
      - { label: 'Descripci√≥n 1 (se muestra lista)', name: 'description', widget: 'string' }
      - { label: 'Descripci√≥n 2 (se muestra en la p√°gina en s√≠)', name: 'lead', widget: 'string' }
      - { label: 'Tags (ej. List [ "tag" ])', name: 'tags', widget: 'string' }
      - { label: 'Fecha de publicaci√≥n', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificaci√≥n', name: 'lastmod', widget: 'datetime' }
      - { label: 'Cuerpo', name: 'body', widget: 'markdown' }
    meta: { path: { widget: string, label: 'Nombre del archivo (ej. "000-t√≠tulopag")', index_file: 'index.md' } }
  - name: 'art√≠culo'
    label: 'Art√≠culo'
    folder: 'content/experimental/'
    create: true
    slug: '{{slug}}'
    nested:
      depth: 2
      summary: '{{title}}'
    editor:
      preview: true
    fields:
      - { label: 'T√≠tulo', name: 'title', widget: "string" }
      - { label: 'Descripci√≥n 1 (se muestra lista)', name: 'description', widget: 'string' }
      - { label: 'Descripci√≥n 2 (se muestra en la p√°gina en s√≠)', name: 'lead', widget: 'string' }
      - { label: 'Fecha de publicaci√≥n', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificaci√≥n', name: 'lastmod', widget: 'datetime' }
      - { label: 'Borrador', name: 'draft', widget: 'boolean', default: true}
      - { label: 'Im√°genes (nombres del archivo, ej. "bbc.png")', name: 'images', widget: 'string', default: "[]" }
      - { label: 'Enlace', name: 'link', widget: 'string', default: '["ENLACE"]' }
      - { label: 'No tocar', name: 'menu', widget: 'text', default: "experimental:\n\tparent: \"general\"" }
      - { label: 'Orden en el men√∫ (menor va primero)', name: 'weight', widget: 'number', default: 10, value_type: "int", min: 10, step: 10 }
      - { label: 'TOC', name: 'toc', widget: 'hidden', default: 'false'}
      - { label: 'Anclado', name: 'pinned', widget: "select", options: [ "true", "false" ], default: false, multiple: true, required: true}
      - { label: 'T√≥picos', name: 'types', widget: 'string', required: true, default: '["Biolog√≠a"]' }
      - { label: 'Categor√≠as', name: 'functionalities', widget: 'string', required: true, default: '["Art√≠culo"]' }
      - { label: 'Extracto', name: 'body', widget: 'markdown', default: "\n```text\nExtracto traducido autom√°ticamente de la \"P√°gina\"\n```\n\nEscribe el extracto aqu√≠." }
    meta: { path: { widget: string, label: 'P√°gina web, no enlace (ej. "bbc.com")', index_file: 'index.md' } }
  - name: 's1'
    label: 'Ciclo I'
    folder: 'content/pregrado/semestre/1/'
    create: true
    slug: "{{title}}"
    editor:
      preview: true
    fields:
      - { label: 'C√≥digo del curso (may√∫sculas)', name: 'title', widget: 'string', default: 'CFO000' }
      - { label: 'Descripci√≥n 1 (se muestra en lista)', name: 'description', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Descripci√≥n 2 (se muestra en la p√°gina en s√≠)', name: 'lead', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Fecha de publicaci√≥n', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificaci√≥n (NO TOCAR)', name: 'lastmod', widget: 'text', default: 'List [ ":git", "lastmod", "date", "publishDate" ]' }
      - { label: 'Borrador', name: 'draft', widget: 'boolean', default: true}
      - { label: 'Im√°genes (no tocar)', name: 'images', widget: 'string', default: "[]" }
      - { label: 'No tocar', name: 'menu', widget: 'text', default: 'Map { "pregrado": Map { "parent": "semestre" } }' }
      - { label: 'Orden en el men√∫ (menor va primero)', name: 'weight', widget: 'number', default: 10, value_type: "int", min: 10, max: 110, step: 10 }
      - { label: 'TOC', name: 'toc', widget: 'hidden', default: 'true'}
      - { label: 'Autor', name: 'contributors', widget: 'string', default: 'David' }
      - { label: 'LaTeX', name: 'math', widget: 'boolean', default: false}
      - { label: 'Cuerpo', name: 'body', widget: 'markdown', default: "\n\\{\\{< alert icon=\"üìå\" text=\"MENSAJE\" \/>\\}\\}\n\n\\<br\\>\n\n\\{\\{ alert icon=\"üëâ\" text=\"REQUISITOS:\" \/>\\}\\}\n\n## T√≠tulo\n\nNo comiences con \"#\". Comienza a partir de ##, luego ### y as√≠.\n\nNota: Tus cambios no se ver√°n instant√°neamente." }
  - name: 's2'
    label: 'Ciclo II'
    folder: 'content/pregrado/semestre/2/'
    create: true
    slug: "{{title}}"
    editor:
      preview: true
    fields:
      - { label: 'C√≥digo del curso (may√∫sculas)', name: 'title', widget: 'string', default: 'CFO000' }
      - { label: 'Descripci√≥n 1 (se muestra en lista)', name: 'description', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Descripci√≥n 2 (se muestra en la p√°gina en s√≠)', name: 'lead', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Fecha de publicaci√≥n', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificaci√≥n (NO TOCAR)', name: 'lastmod', widget: 'text', default: "- :git\n- lastmod\n- date\n- publishDate" }
      - { label: 'Borrador', name: 'draft', widget: 'boolean', default: true}
      - { label: 'Im√°genes (no tocar)', name: 'images', widget: 'string', default: "[]" }
      - { label: 'No tocar', name: 'menu', widget: 'text', default: "pregrado:\n\tparent: \"semestre\"" }
      - { label: 'Orden en el men√∫ (menor va primero)', name: 'weight', widget: 'number', default: 10, value_type: "int", min: 10, max: 110, step: 10 }
      - { label: 'TOC', name: 'toc', widget: 'hidden', default: 'true'}
      - { label: 'Autor', name: 'contributors', widget: 'string', default: 'David' }
      - { label: 'LaTeX', name: 'math', widget: 'boolean', default: false}
      - { label: 'Cuerpo', name: 'body', widget: 'markdown', default: "\n\\{\\{< alert icon=\"üìå\" text=\"MENSAJE\" \/>\\}\\}\n\n\\<br\\>\n\n\\{\\{ alert icon=\"üëâ\" text=\"REQUISITOS:\" \/>\\}\\}\n\n## T√≠tulo\n\nNo comiences con \"#\". Comienza a partir de ##, luego ### y as√≠.\n\nNota: Tus cambios no se ver√°n instant√°neamente." }
  - name: 's3'
    label: 'Ciclo III'
    folder: 'content/pregrado/semestre/3/'
    create: true
    slug: "{{title}}"
    editor:
      preview: true
    fields:
      - { label: 'C√≥digo del curso (may√∫sculas)', name: 'title', widget: 'string', default: CFO000 }
      - { label: 'Descripci√≥n 1 (se muestra en lista)', name: 'description', widget: 'string', default: CFO000 ‚Äî 0 cr√©ditos }
      - { label: 'Descripci√≥n 2 (se muestra en la p√°gina en s√≠)', name: 'lead', widget: 'string', default: CFO000 ‚Äî 0 cr√©ditos }
      - { label: 'Fecha de publicaci√≥n', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificaci√≥n (NO TOCAR)', name: 'lastmod', widget: 'text', default: 'List [ ":git", "lastmod", "date", "publishDate" ]' }
      - { label: 'Borrador', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Im√°genes (no tocar)', name: 'images', widget: 'string', default: 'List []' }
      - { label: 'No tocar', name: 'menu', widget: 'text', default: 'Map { "pregrado": Map { "parent": "semestre" } }' }
      - { label: 'Orden en el men√∫ (menor va primero)', name: 'weight', widget: 'number', default: 10, value_type: "int", min: 10, max: 110, step: 10 }
      - { label: 'TOC', name: 'toc', widget: 'hidden', default: 'true'}
      - { label: 'Autor', name: 'contributors', widget: 'string', default: ["David"] }
      - { label: 'LaTeX', name: 'math', widget: 'boolean', default: false}
      - { label: 'Cuerpo', name: 'body', widget: 'markdown', default: "\n\\{\\{< alert icon=\"üìå\" text=\"MENSAJE\" \/>\\}\\}\n\n\\<br\\>\n\n\\{\\{ alert icon=\"üëâ\" text=\"REQUISITOS:\" \/>\\}\\}\n\n## T√≠tulo\n\nNo comiences con \"#\". Comienza a partir de ##, luego ### y as√≠.\n\nNota: Tus cambios no se ver√°n instant√°neamente." }
  - name: 's4'
    label: 'Ciclo IV'
    folder: 'content/pregrado/semestre/4/'
    create: true
    slug: "{{title}}"
    editor:
      preview: true
    fields:
      - { label: 'C√≥digo del curso (may√∫sculas)', name: 'title', widget: 'string', default: 'CFO000' }
      - { label: 'Descripci√≥n 1 (se muestra en lista)', name: 'description', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Descripci√≥n 2 (se muestra en la p√°gina en s√≠)', name: 'lead', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Fecha de publicaci√≥n', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificaci√≥n (NO TOCAR)', name: 'lastmod', widget: 'text', default: "- :git\n- lastmod\n- date\n- publishDate" }
      - { label: 'Borrador', name: 'draft', widget: 'boolean', default: true}
      - { label: 'Im√°genes (no tocar)', name: 'images', widget: 'string', default: "[]" }
      - { label: 'No tocar', name: 'menu', widget: 'text', default: "pregrado:\n\tparent: \"semestre\"" }
      - { label: 'Orden en el men√∫ (menor va primero)', name: 'weight', widget: 'number', default: 10, value_type: "int", min: 10, max: 110, step: 10 }
      - { label: 'TOC', name: 'toc', widget: 'hidden', default: 'true'}
      - { label: 'Autor', name: 'contributors', widget: 'string', default: 'David' }
      - { label: 'LaTeX', name: 'math', widget: 'boolean', default: false}
      - { label: 'Cuerpo', name: 'body', widget: 'markdown', default: "\n\\{\\{< alert icon=\"üìå\" text=\"MENSAJE\" \/>\\}\\}\n\n\\<br\\>\n\n\\{\\{ alert icon=\"üëâ\" text=\"REQUISITOS:\" \/>\\}\\}\n\n## T√≠tulo\n\nNo comiences con \"#\". Comienza a partir de ##, luego ### y as√≠.\n\nNota: Tus cambios no se ver√°n instant√°neamente." }
  - name: 's5'
    label: 'Ciclo V'
    folder: 'content/pregrado/semestre/5/'
    create: true
    slug: "{{title}}"
    editor:
      preview: true
    fields:
      - { label: 'C√≥digo del curso (may√∫sculas)', name: 'title', widget: 'string', default: 'CFO000' }
      - { label: 'Descripci√≥n 1 (se muestra en lista)', name: 'description', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Descripci√≥n 2 (se muestra en la p√°gina en s√≠)', name: 'lead', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Fecha de publicaci√≥n', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificaci√≥n (NO TOCAR)', name: 'lastmod', widget: 'text', default: "- :git\n- lastmod\n- date\n- publishDate" }
      - { label: 'Borrador', name: 'draft', widget: 'boolean', default: true}
      - { label: 'Im√°genes (no tocar)', name: 'images', widget: 'string', default: "[]" }
      - { label: 'No tocar', name: 'menu', widget: 'text', default: "pregrado:\n\tparent: \"semestre\"" }
      - { label: 'Orden en el men√∫ (menor va primero)', name: 'weight', widget: 'number', default: 10, value_type: "int", min: 10, max: 110, step: 10 }
      - { label: 'TOC', name: 'toc', widget: 'hidden', default: 'true'}
      - { label: 'Autor', name: 'contributors', widget: 'string', default: 'David' }
      - { label: 'LaTeX', name: 'math', widget: 'boolean', default: false}
      - { label: 'Cuerpo', name: 'body', widget: 'markdown', default: "\n\\{\\{< alert icon=\"üìå\" text=\"MENSAJE\" \/>\\}\\}\n\n\\<br\\>\n\n\\{\\{ alert icon=\"üëâ\" text=\"REQUISITOS:\" \/>\\}\\}\n\n## T√≠tulo\n\nNo comiences con \"#\". Comienza a partir de ##, luego ### y as√≠.\n\nNota: Tus cambios no se ver√°n instant√°neamente." }
  - name: 's6'
    label: 'Ciclo VI'
    folder: 'content/pregrado/semestre/6/'
    create: true
    slug: "{{title}}"
    editor:
      preview: true
    fields:
      - { label: 'C√≥digo del curso (may√∫sculas)', name: 'title', widget: 'string', default: 'CFO000' }
      - { label: 'Descripci√≥n 1 (se muestra en lista)', name: 'description', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Descripci√≥n 2 (se muestra en la p√°gina en s√≠)', name: 'lead', widget: 'string', default: 'CFO000 ‚Äî 0 cr√©ditos' }
      - { label: 'Fecha de publicaci√≥n', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificaci√≥n (NO TOCAR)', name: 'lastmod', widget: 'text', default: "- :git\n- lastmod\n- date\n- publishDate" }
      - { label: 'Borrador', name: 'draft', widget: 'boolean', default: true}
      - { label: 'Im√°genes (no tocar)', name: 'images', widget: 'string', default: "[]" }
      - { label: 'No tocar', name: 'menu', widget: 'text', default: "pregrado:\n\tparent: \"semestre\"" }
      - { label: 'Orden en el men√∫ (menor va primero)', name: 'weight', widget: 'number', default: 10, value_type: "int", min: 10, max: 110, step: 10 }
      - { label: 'TOC', name: 'toc', widget: 'hidden', default: 'true'}
      - { label: 'Autor', name: 'contributors', widget: 'string', default: 'David' }
      - { label: 'LaTeX', name: 'math', widget: 'boolean', default: false}
      - { label: 'Cuerpo', name: 'body', widget: 'markdown', default: "\n\\{\\{< alert icon=\"üìå\" text=\"MENSAJE\" \/>\\}\\}\n\n\\<br\\>\n\n\\{\\{ alert icon=\"üëâ\" text=\"REQUISITOS:\" \/>\\}\\}\n\n## T√≠tulo\n\nNo comiences con \"#\". Comienza a partir de ##, luego ### y as√≠.\n\nNota: Tus cambios no se ver√°n instant√°neamente." }