name: ðŸ•·ï¸ Algolia Crawler

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '/content/'

jobs:
  algolia_recrawl:
    name: Algolia Recrawl

    runs-on: ubuntu-latest

    steps:
      - name: Inicializar Github Action
        uses: actions/checkout@v4

      - name: Cloudflare-MAIN => Algolia
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.10
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-name: ${{ secrets.CRAWLER_NAME }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://caefisica.com/'
          override-config: false
